title: Compétences 21
author: Assina
email: assinam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ce blog veut aider les jeunes filles à se diriger vers des métiers numériques.

# social links
twitter_username: assimay 
github_username:  assinam

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
